// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Repository;

#nullable disable

namespace ProvaPub.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20240926220246_changes")]
    partial class changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Melanie Ullrich"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Travis Dare"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Joan Conn"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tony Cormier"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Domingo Zboncak"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Willie Windler"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ed Sipes"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Derek Nolan"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Harriet Hettinger"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Brooke Grady"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Israel Heaney"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Henrietta Beier"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Wilbur Keeling"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Melinda Beatty"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Saul Goldner"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Shannon Dare"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Elvira Fay"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Brittany Jakubowski"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Shannon Nitzsche"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Juanita Mills"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Handmade Frozen Chair"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantastic Frozen Ball"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Incredible Fresh Mouse"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ergonomic Soft Shirt"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sleek Concrete Hat"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Refined Steel Soap"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Handcrafted Cotton Hat"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Small Fresh Towels"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tasty Frozen Cheese"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tasty Steel Computer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Practical Soft Car"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Fantastic Metal Bike"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Intelligent Steel Chips"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Sleek Plastic Cheese"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Intelligent Metal Computer"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Small Soft Tuna"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Intelligent Granite Sausages"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Rustic Plastic Car"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Fantastic Fresh Salad"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Unbranded Granite Bike"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.HasOne("ProvaPub.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
